# Generated by Django 3.1.7 on 2021-05-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Database',
            fields=[
                ('product_name', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('link', models.CharField(max_length=70)),
            ],
        ),
    ]
